"""Generate the synthetic renewal quote used to exercise the document reader.

    py -3.12 tools_make_quote.py

Writes ``data/sample_renewal_quote.pdf``. Needs ``reportlab``, which is a
development dependency only -- the PDF is committed, so nothing on a deployment
regenerates it and reportlab is deliberately absent from requirements.txt.

**Everything in this document is invented.** The reseller, the customer, the
quote number, the contacts and every figure are fictional, and each page carries
a banner saying so. Product names are real because a licensing document has to
name the products it licenses; nothing here is presented as issued by, endorsed
by, or originating from any real company. It exists to be uploaded to the reader
on Estate discovery so the extraction path can be tested without touching a
client's own commercial paperwork.

The content is shaped to exercise the entitlement schema rather than to read
nicely. It contains, deliberately:

* a renewal date and a core count stated once, exactly, in different places
* two editions at different per-core rates, plus a stated blended rate -- so the
  reader has a figure to report rather than a division to perform
* a price cap and a ramp-down that are explicitly *refused*, which the schema
  asks about and which a careless reader would return as null
* portability language that is real but conditional, which should surface in the
  notes rather than resolve to a confident true or false
* perpetual licences named as out of scope, which is the perpetual-key exposure
* several pages of ordinary commercial noise that none of the fields want
"""

import pathlib

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (KeepTogether, Paragraph, SimpleDocTemplate, Spacer,
                                Table, TableStyle)

OUT = pathlib.Path("data/sample_renewal_quote.pdf")

INK = colors.HexColor("#1a1a1a")
MUTED = colors.HexColor("#666666")
RULE = colors.HexColor("#cccccc")
BANNER_BG = colors.HexColor("#FFF3CD")
BANNER_INK = colors.HexColor("#7A5C00")

styles = getSampleStyleSheet()
S = {
    "h1": ParagraphStyle("h1", parent=styles["Normal"], fontName="Helvetica-Bold",
                         fontSize=16, leading=20, textColor=INK, spaceAfter=2),
    "h2": ParagraphStyle("h2", parent=styles["Normal"], fontName="Helvetica-Bold",
                         fontSize=10.5, leading=14, textColor=INK,
                         spaceBefore=12, spaceAfter=4),
    "body": ParagraphStyle("body", parent=styles["Normal"], fontName="Helvetica",
                           fontSize=8.8, leading=12.5, textColor=INK, spaceAfter=4),
    "small": ParagraphStyle("small", parent=styles["Normal"], fontName="Helvetica",
                            fontSize=7.6, leading=10.5, textColor=MUTED),
    "banner": ParagraphStyle("banner", parent=styles["Normal"],
                             fontName="Helvetica-Bold", fontSize=8.2, leading=11,
                             textColor=BANNER_INK, alignment=1),
}


def para(text, style="body"):
    return Paragraph(text, S[style])


def banner():
    """Unmissable, on every page. This must never be mistaken for a real quote."""
    t = Table([[para(
        "SYNTHETIC SAMPLE &mdash; NOT A REAL QUOTATION. Generated by "
        "tools_make_quote.py to test document extraction. The reseller, customer, "
        "quote number, contacts and every figure below are invented.", "banner")]],
        colWidths=[170 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BANNER_BG),
        ("BOX", (0, 0), (-1, -1), 0.6, BANNER_INK),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def grid(rows, widths, header=True, align_right=()):
    t = Table(rows, colWidths=widths, hAlign="LEFT")
    style = [
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.4),
        ("TEXTCOLOR", (0, 0), (-1, -1), INK),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, RULE),
    ]
    if header:
        style += [("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                  ("LINEBELOW", (0, 0), (-1, 0), 0.9, INK)]
    for col in align_right:
        style.append(("ALIGN", (col, 0), (col, -1), "RIGHT"))
    t.setStyle(TableStyle(style))
    return t


def build() -> list:
    f = []
    f.append(banner())
    f.append(Spacer(1, 8))

    # ---- letterhead ------------------------------------------------------
    f.append(para("Northgate Technology Partners Ltd", "h1"))
    f.append(para("Licensing &amp; Renewals Desk &nbsp;|&nbsp; 14 Wharfside Court, "
                  "Manchester M15 4RB &nbsp;|&nbsp; renewals@northgate-tp.example", "small"))
    f.append(Spacer(1, 10))

    f.append(grid([
        ["Quotation reference", "NTP-RN-2026-04417"],
        ["Issued", "12 August 2026"],
        ["Valid until", "26 September 2026"],
        ["Prepared for", "Merrivale Assurance Group plc"],
        ["Account manager", "D. Okonkwo"],
        ["Customer reference", "PO to be raised against MSA-2021-0088"],
    ], [45 * mm, 125 * mm], header=False))

    # ---- the two figures the whole programme is timed against ------------
    f.append(para("1. Subscription renewal &mdash; summary", "h2"))
    f.append(para(
        "This quotation covers renewal of the customer's VMware subscription "
        "entitlement across the Manchester and Leeds data centres. The current "
        "subscription term <b>expires on 30 November 2026</b>. Renewal must be "
        "completed on or before that date to avoid a lapse in support entitlement "
        "and the late-renewal uplift set out in section 5."))
    f.append(para(
        "Total licensed capacity under this quotation is <b>2,112 physical cores</b> "
        "across 44 hosts. Core counts have been taken from the configuration data "
        "supplied by the customer on 3 August 2026 and should be reconfirmed before "
        "a purchase order is raised."))

    # ---- line items ------------------------------------------------------
    f.append(para("2. Licensed products and rates", "h2"))
    f.append(grid([
        ["Product", "Hosts", "Cores", "Rate / core / yr", "Annual"],
        ["VMware Cloud Foundation 9.1", "32", "1,536", "USD 172.00", "USD 264,192.00"],
        ["vSphere Foundation 9.1", "12", "576", "USD 118.00", "USD 67,968.00"],
        ["Total", "44", "2,112", "USD 157.27 blended", "USD 332,160.00"],
    ], [58 * mm, 16 * mm, 20 * mm, 36 * mm, 40 * mm], align_right=(1, 2, 3, 4)))
    f.append(Spacer(1, 4))
    f.append(para(
        "Rates are per physical core per year and are exclusive of VAT. The blended "
        "rate above is stated for convenience and is <b>USD 157.27 per core per "
        "year</b>. Licensing is subject to a minimum of 16 cores per CPU socket; "
        "based on the configuration supplied, no socket falls below that threshold "
        "and no minimum uplift arises.", "small"))

    f.append(para("3. Term and totals", "h2"))
    f.append(grid([
        ["Committed term", "3 years, commencing 1 December 2026"],
        ["Annual subscription", "USD 332,160.00"],
        ["Total term value", "USD 996,480.00"],
        ["Prior term annual", "USD 214,940.00 (expiring 30 November 2026)"],
        ["Increase on prior term", "54.5%"],
        ["Support tier", "Production Support, 24x7, included"],
    ], [50 * mm, 120 * mm], header=False))

    # ---- the refusals the schema asks about -----------------------------
    f.append(KeepTogether([
        para("4. Commercial terms", "h2"),
        para(
            "<b>4.1 Renewal pricing.</b> Pricing is held for the committed term only. "
            "<b>No renewal price cap is offered under this quotation</b>, and no "
            "undertaking is given as to pricing at the next renewal cycle. Any "
            "subsequent term will be quoted at the rates then in force."),
        para(
            "<b>4.2 Entitlement adjustment.</b> Entitlement is fixed for the committed "
            "term. <b>Mid-term reductions are not permitted</b> and no ramp-down "
            "structure is available against this quotation. Additional cores may be "
            "added at the rates in section 2, co-terminating with the committed term."),
        para(
            "<b>4.3 Growth cores.</b> Cores added during the term are charged at the "
            "prevailing list rate at the date of addition. No price hold is offered on "
            "growth capacity."),
        para(
            "<b>4.4 Portability.</b> Portability of subscription entitlement to "
            "hyperscaler platforms is governed by the vendor's then-current programme "
            "terms. It is <b>not warranted under this quotation</b> and the customer "
            "should seek written confirmation from the vendor before relying on it in "
            "any migration plan."),
    ]))

    # ---- the out-of-scope exposure --------------------------------------
    f.append(KeepTogether([
        para("5. Exclusions and customer notes", "h2"),
        para(
            "<b>5.1 Perpetual licences.</b> Nine hosts in the Leeds facility remain on "
            "<b>perpetual vSphere 7 Enterprise Plus licences</b> with lapsed support. "
            "These are <b>not covered by this quotation</b> and cannot be renewed under "
            "the current programme. They are recorded here so the customer's entitlement "
            "position is complete; a separate conversation is required."),
        para(
            "<b>5.2 Late renewal.</b> Where renewal completes after 30 November 2026, a "
            "reinstatement uplift of 20% of the first-year subscription applies, "
            "together with any lapsed-period charge assessed by the vendor."),
        para(
            "<b>5.3 vSAN capacity.</b> vSAN entitlement is included with VMware Cloud "
            "Foundation at 1 TiB per core. Capacity in excess of the included "
            "allowance is chargeable and is not quoted here."),
        para(
            "<b>5.4 Configuration data.</b> Core counts derive from customer-supplied "
            "data and have not been independently audited. Northgate accepts no "
            "liability for shortfall arising from an inaccurate declaration."),
    ]))

    # ---- ordinary noise the schema does not want ------------------------
    f.append(KeepTogether([
        para("6. Payment and administration", "h2"),
        grid([
            ["Payment terms", "30 days net from invoice date"],
            ["Invoicing", "Annually in advance, first invoice on activation"],
            ["Purchase order", "Required; quote reference must appear on the PO"],
            ["Currency", "USD. FX at the rate prevailing on the invoice date"],
            ["Delivery", "Electronic. Entitlement keys issued within 5 working days"],
            ["Escalation", "renewals@northgate-tp.example, then account manager"],
        ], [45 * mm, 125 * mm], header=False),
        Spacer(1, 6),
        para(
            "This quotation is issued subject to Northgate Technology Partners' standard "
            "terms of business and to the vendor's end user licence agreement. It does "
            "not constitute an offer capable of acceptance until countersigned. Figures "
            "are exclusive of VAT and of any third-party professional services. E&amp;OE.",
            "small"),
        Spacer(1, 8),
        banner(),
    ]))
    return f


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(OUT), pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title="Sample renewal quotation (synthetic)",
        author="tools_make_quote.py",
        subject="Synthetic test fixture -- not a real quotation",
    )
    doc.build(build())
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")
    print("\nWhat a correct extraction should return:")
    for k, v in {
        "renewal_date": "30 November 2026",
        "entitled_cores": "2112",
        "editions": "VMware Cloud Foundation 9.1, vSphere Foundation 9.1",
        "term_years": "3",
        "quoted_cost_per_year": "332160.00",
        "currency": "USD",
        "cost_per_core_per_year": "157.27  (stated, not divided)",
        "perpetual_key_exposure": "true  (nine hosts on perpetual vSphere 7)",
        "price_cap_offered": "false  (explicitly refused in 4.1)",
        "ramp_down_offered": "false  (explicitly refused in 4.2)",
        "portability_language": "false  (conditional, not warranted -- 4.4)",
    }.items():
        print(f"  {k:26s} {v}")
    print("  notes                      should flag 4.4 as conditional, and that\n"
          "                             core counts are unaudited")


if __name__ == "__main__":
    main()
